### ISSUE TITLE
node queries

### ISSUE THREAD

**Issue by spicysomtam** [propyless/panopuppet#149] opened 2016-06-24 15:31 UTC
Not sure if I am missing something here, but I wanted to do a node query like:

```
"and",["=", ["fact", "systemuse"], "data-protector"],["=",["fact", "osfamily"],"RedHat"]
```

As alluded to here: https://docs.puppet.com/puppetdb/2.3/api/query/v3/nodes.html

This works in puppetboard/curl/etc.

How would we do this query in pano?

I know we can do fact queries like this:

```
"and",["=","name","operatingsystem"],["=","value","OracleLinux"]
```

**Comment by propyless** [comment] 2016-06-25 06:07
This ticket is a duplicate of #137 
Right now its not possible.

**Closed by propyless** 2016-06-25 06:07 UTC
Labels: duplicate
